version: "3"

services:

  laracom_php:
    build:
      context: ./php
    image: "${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_php:${IMAGE_TAG}"
    container_name: "${REPOSITORY_NAME}_php"
    hostname: "laracom-php"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html


  laracom_nginx:
    build:
      context: ./nginx
    image: "${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_nginx:${IMAGE_TAG}"
    container_name: "${REPOSITORY_NAME}_nginx"
    hostname: "laracom-nginx"
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laracom_php

